apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azuredisk-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
